### ISSUE TITLE
Plotting samples to example.pdf...Error in x[j] : invalid subscript type 'list'

### ISSUE THREAD

**Issue by raymond301** [RCollins13/CNView#1]
Have an input file with coverage from 30 samples, across 1 gene.
Each row in the bed file covers 100bp, like shown in your example.
Here is my command: 
```
/data2/bsi/staff_analysis/m088378/CNView.R 17 41205689 41277589 PDXsamples.names.txt PDXsamples.chrless.bed example.pdf --probs
```
I am following the format exactly specified. However I get this error:

```
+-------------------+
| CNView Visualizer |
|     (c) 2016      |
+-------------------+
Reading sample IDs from PDXsamples.names.txt
Filtering & loading coverage matrix... Complete
Compressing coverage matrix [900 bp bins]...  Complete
Performing intra-sample normalization... Complete
Performing inter-sample normalization... Complete
Plotting samples to example.pdf...Error in x[j] : invalid subscript type 'list'
Calls: CNView -> pt -> [ -> [.data.frame
Execution halted
```

I'm going to start going through the code step by step, but I thought I'd create an issue to make you aware of a potential situation that the code is not handling.

**Comment by raymond301** [comment]
As I was digging into the code, I did discover a different issue. Semi-unrelated.

Line 206:
```R
##Generate Colors##
      if(pt(plotSet[1,sampIdx[k]],df=(ncol(plotSet)-8)) >= 1-(0.05/(ncol(plotSet)-7))){
        colval <- "blue"
      }else if(pt(plotSet[1,sampIdx[k]],df=(ncol(plotSet)-8)) <= 0.05/(ncol(plotSet)-7)){
        colval <- "red"
      }else{
        colval <- "gray40"
      }
```

The 1st sample name I provided was "sample3-1", which caused
```R
sampIdx[k] = integer(0)
```

I'm still working on the original issue, but error handling names with hyphens would be a nice addition. I'll just avoid it for this version.

**Comment by RCollins13** [comment]
Thanks for raising these issues. The "invalid subscript type" error usually occurs when either there are no lines in the input file or the sample IDs specified aren't in the header of the input matrix.

Could you post a head of ```PDXsamples.chrless.bed``` as well as the contents of ```PDXsamples.names.txt```?

Also, are the bins in your input matrix uniform sized and continuous from the start of your plot window to the end? 

Currently, CNView doesn't support nonuniform bin sizes like exome data; I've been playing with some modifications to adapt to these data types and may include them as features in the future.

Thanks for the note about hyphens in sample IDs -- this should be an easy fix, and I can include it in the next future update.

Ryan

**Comment by raymond301** [comment]
I've figure out the culprit of the error...unsure how to fix it.

The variable "sampIdx" is parsing the columns and names, and overlapping the column indexes.
Here's the print out of that variable, with my inputs.
```
$s_Panc3_1
[1] 4
$s_Pax101_F2AR
[1] 5
$s_Pax102_F2
[1] 6
$s_Pax110_F2AR
[1] 7
$s_Pax113_F2AR
[1] 8
$s_Pax124_F2AL
[1] 9
$s_PAX12
[1]  9 10
$s_Pax79_F3AL
[1] 32
$s_Pax82_F2
[1] 33
$s_Pax89_F3AR
[1] 34
$s_Pax97_F2DR
[1] 35
$s_PAX9
[1] 35 36
```

Note how samples s_PAX12 & s_PAX9 double up with their neighbors.

Here are the head of my input files.
[PDXsamples.chrless.head.txt](https://github.com/RCollins13/CNView/files/226391/PDXsamples.chrless.head.txt)
[PDXsamples.names.head.txt](https://github.com/RCollins13/CNView/files/226392/PDXsamples.names.head.txt)

**Comment by RCollins13** [comment]
Great, this makes the error very clear. I have implemented a fix and pushed it to the master; try pulling the updated version and rerunning now.

The issue was the implementation of R ```grep()``` to subselect the appropriate sample ID from the column indexes. However, ```grep()``` was only searching for partial substring matches instead of exact matches. I wrapped the sample IDs in word boundaries (```\b```) to get around it.

This should fix the issue, but please let me know if it does not.

Ryan

**Comment by raymond301** [comment]
Great it works! Thank you for the very quick response.
