### ISSUE TITLE
Sample Name issue

### ISSUE THREAD

**Issue by raymond301** [RCollins13/CNView#3]
I discovered that if the sample name has a hyphen in it, the program errors out. 
Like this:
>+-------------------+
>| CNView Visualizer |
>|     (c) 2016      |
>+-------------------+
>Reading sample IDs from samplenames.txt
>Filtering & loading coverage matrix... Complete
>Compressing coverage matrix [600 bp bins]...  Complete
>Performing intra-sample normalization... Complete
>Performing inter-sample normalization... Complete
>Plotting samples to myExample.pdf...Error in x[j] : invalid subscript type 'list'
>Calls: CNView -> pt -> [ -> [.data.frame
>Execution halted

When I take the hyphens out of the sample names, everything works fine.

Cheers!

**Comment by RCollins13** [comment]
Thanks for reminding me about this issue; I recall you had mentioned it previously.

Fortunately it was an easy fix. If you pull the new commit from master you should be able to include samples with hyphens in their names.

I've included a few new features in this commit, although I'm still working on a better backend interface for hg38/hg18 and non-human reference genomes through UCSC, too. That might take a bit longer.

-Ryan
