### ISSUE TITLE
CNV visualization for CNVnator output 

### ISSUE THREAD

**Issue by bhuwankhatri11** [RCollins13/CNView#4]
Hi I have CNV output file like:
chr	start	end	cnv
10	742501	778500	1.30923
10	1726501	1755000	1.17241
10	1761001	2217000	1.38026
10	14281501	14355000	1.37233
10	17359501	17797500	1.44288
How can I use CNview tool to view deletion or duplication?

**Comment by RCollins13** [comment]
Hi bhuwankhatri11,

If your CNVs listed above were discovered from whole-genome sequencing, you'll need to first generate binned coverage of your chromosomes of interest before CNView visualization.

For instructions on how to generate this data, please see the documentation, [available here](https://github.com/RCollins13/CNView#getting-started).

Ryan
