### ISSUE TITLE
Strange Values in Plots - 

### ISSUE THREAD

**Issue by B1T0** [RCollins13/CNView#7]
Hi @RCollins13,

I tried to use CNView for one of my projects. Sadly my results have nothing in common with your examples in the README:

- The Median t Score is always 0 (no fluctuations)
- The MADs are always 1/-1 or 2/-2 (no fluctuations)
- I don't get p-values but q-values
- The q-value is always 1

To create the plots I used the following commands:
```
# Create raw coverage matrices
bedtools makewindows -b important_region.bed -w 100 > windows.bed
bedtools coverage -a windows.bed -b iddm.bam > covmat_iddm.bed
bedtools coverage -a windows.bed -b 1AR1.bam > covmat_1AR1.bed

# Clean coverage matrices
awk -v OFS='\t' '{ print $1,$2,$3,$4 }' covmat_iddm.bed > covmat_iddm_cln.bed
awk -v OFS='\t' '{ print $1,$2,$3,$4 }' covmat_1AR1.bed > covmat_1AR1_cln.bed

# Create union
bedtools unionbedg -header -i covmat_iddm_cln.bed covmat_1AR1_cln.bed > covmat_union.bed

# Create Plots
./CNView.R -u 1 242913201 242961750 this covmat_union.bed deletion.pdf  --ymin -6 --ymax 10 --probs
```

Here is one example for a plot I get: 
[deletion.pdf](https://github.com/RCollins13/CNView/files/1506336/deletion.pdf)

And here is the corresponding Coverage Matrix (I had to change the file extension from bed to txt to upload it here):
[small_covmat.txt](https://github.com/RCollins13/CNView/files/1506345/small_covmat.txt)

Is there anything I did not understand correctly to use your program or do you think I have errors in my data?

Thanks,
Tobi

**Comment by RCollins13** [comment]
Hi @B1To,

Thanks for getting in touch.

Everything you've done is correct. However, binCov requires a population of samples (typically >20-30, ideally ~hundreds) to normalize observed coverage data per sample against expectations calculated based on the other samples in the population.

The matrix you posted looks like there are only two samples present. Any chance you have more samples you could include in this analysis? 

Repeating the same process as you have done with, say, >30 samples should return interpretable results.

Best,
Ryan

**Comment by B1T0** [comment]
Hi @RCollins13 ,

thank you for your helpful answer. I tried to add more samples and now it gives me better results. Thanks again for your software!

Best,
Tobi
